title: Yang Zhou
role: PhD student at Harvard
logo: ./pic/self.jpg
description: "<br>yangzhou (at) g.harvard.edu<br>yanggepkuer15 (at) gmail.com<br><br>SEC 4.429,<br>150 Western Ave,<br>Allston, MA 02134"
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
