title: Yang Zhou
role: PhD student at Harvard
logo: ./pic/self.jpg
description: "<br>yangzhou (at) g.harvard.edu<br>yanggepkuer15 (at) gmail.com<br><br>SEC 4.429,<br>150 Western Ave,<br>Allston, MA 02134<br><br><a href=\"https://scholar.google.com/citations?user=c3KgJJ8AAAAJ\">View My Google Scholar</a>"
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal

plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%b %d, 20%y'