title: Yang Zhou
role: yangzhou.rpc@gmail.com
logo: ./pic/zy5.jpg
description: "Me (the left one)<br><br><a href=\"https://scholar.google.com/citations?user=c3KgJJ8AAAAJ\">Google Scholar</a> | <a href=\"./cv_yang.pdf\">CV</a> | <a href=\"./bio.txt\">Bio</a>"
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal

plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%b %d, 20%y'
